services:
  localstack:
    image: localstack/localstack:3.8
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3
      DEBUG: "1"
      AWS_DEFAULT_REGION: us-east-1
      PERSISTENCE: "1"
    volumes:
      - "./localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      
  api:
      build: .
      container_name: sentiment-api

      ports:
        - "5000:5000"

      environment:
        AWS_ACCESS_KEY_ID: test
        AWS_SECRET_ACCESS_KEY: test
        AWS_DEFAULT_REGION: us-east-1
        AWS_ENDPOINT_URL: http://localstack:4566
        BUCKET_NAME: sentiment-model-bucket

      depends_on:
        - localstack